name: clean_architecture_example
description: A new Flutter project using Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  path_provider: ^2.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/fonts/
